modLoader="javafml"
loaderVersion="[40,)"
license="MIT"

[[mods]]
modId="dtbyg"
version="${file.jarVersion}"
displayName="Dynamic Trees for BYG"
#updateJSONURL="https://github.com/supermassimo/DynamicTrees-ExC/blob/1.12.2/.DONE/DynamicTrees-BYG/version_info.json?raw=true" #optional
#displayURL="https://www.curseforge.com/minecraft/mc-mods/dynamic-trees-byg" #optional
logoFile=""
credits=""
authors="Max Hyper, Harley O' Connor, Corgi Taco, SuperCoder79"
description='''
Compatibility Mod between Dynamic trees and Oh The Biomes You'll Go
'''

[[dependencies.dtbyg]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dtbyg]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dtbyg]]
    modId="dynamictrees"
    mandatory=true
    versionRange="[0.11.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.dtbyg]]
    modId="dynamictreesplus"
    mandatory=false
    versionRange="[0.2.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.dtbyg]]
    modId="byg"
    mandatory=true
    versionRange="[1.4,2.0)"
    ordering="AFTER"
    side="BOTH"
